bot:
  uin: 1
  groups:
    - 100
    - 101
    - 102
  superusers:
    - 200
    - 201

function:
  forwardToGame:
    enabled: true
    prefix: ""
    forced: false
  forwardToGroup:
    enabled: true
    prefix: "!"
    forced: false
  destinationControl:
    enabled: true
    bindingRequired: false